# Generated by Django 4.1.7 on 2023-03-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_account_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
